@startuml mackerel-awslambda-agent - mackerel aws lambda agent

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/ApplicationIntegration/SQS.puml

left to right direction

agent "Mackerel" as mackerel #fff

SQS(reportQueue, "Report Queue", "check Reports")
SimpleStorageServiceS3(config, "Mackerel config", "mackerel configfile")
Lambda(sender, "sender", "Post a report to mackerel")
Lambda(checks1, "checks", "check plugin 1")
Lambda(checks2, "checks", "check plugin 2")
Lambda(checks3, "checks", "check plugin 3")
Lambda(invoker, "invoker", "plugin invoker")

config -> invoker : load config
invoker --> checks1 : "async invoke"
invoker --> checks2 : "async invoke"
invoker --> checks3 : "async invoke"
checks1 --> reportQueue : send report
checks2 --> reportQueue : send report
checks3 --> reportQueue : send report
reportQueue <-- sender : poling
sender -> mackerel

@enduml


